# Theme - Minimal
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-remote-theme

# Configuration / Settings
show_downloads: false
title: "Eyan Documet"
description: "Mechanical Engineering graduate (BSME '25) specializing in mechatronics and R&D."
color-scheme: auto
logo: /assets/img/mugshot.png
favicon: true
hide_project_page: true
favicon: true

# Sidebar
platforms:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/eyandocumet
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:eyan.documet@protonmail.com
  - name: Phone
    icon: <i class="fa-solid fa-phone"></i>
    link: tel:+13194805366

navigation:
  - name: Portfolio
    link: https://eyandocumet.xyz/
    sublist:
      - name: Gyroid Experiment
        link: https://eyandocumet.xyz/projects/gyroid.html
      - name: PyroBot
        link: https://eyandocumet.xyz/projects/pyrobot.html
      - name: Finite Elements
        link: https://eyandocumet.xyz/projects/myfem.html
      - name: Inchworm
        link: https://eyandocumet.xyz/projects/inchworm.html

